Configure build process

diff --git a/.github/workflows/deploy_runner.yaml b/.github/workflows/deploy_runner.yaml
--- a/.github/workflows/deploy_runner.yaml
+++ b/.github/workflows/deploy_runner.yaml
@@ -90,58 +90,59 @@ jobs:
             echo "❌ Pod $pod did not become ready in time"
             exit 1
           }
+          echo "Getting consul-bootstrap-acl-token"
           kubectl get secrets -n consul-ns
-          kubectl get secret consul-bootstrap-acl-token -n consul-ns -o jsonpath='{.data}' \
-            | jq -r 'to_entries[] | "\(.key): \(.value | @base64d)"'
+          token=$(kubectl get secret consul-bootstrap-acl-token -n consul-ns -o jsonpath='{.data.token}' | base64 --decode)
+          echo "Consul Token: $token"
+          echo "CONSUL_TOKEN=$token" >> $GITHUB_ENV
 
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-#      - name: Checkout Code
-#        uses: actions/checkout@v4
-#
-#      - name: Install Playwright Runner
-#        run: |
-#          ls -l
-#          helm install --namespace=playwright-runner --create-namespace -f ./deployments/charts/atp3-playwright-runner/values.yaml -f ./deployments/charts/atp3-playwright-runner/resource-profiles/dev.yaml atp3-playwright-runner ./deployments/charts/atp3-playwright-runner --set DOCKER_TAG="ghcr.io/netcracker/qubership-testing-platform-playwright-runner:build_process_latest"
-#
-#      - name: Get docker images
-#        shell: bash
-#        run: |
-#          echo "▶️ Checking pods in namespace playwright-runner"
-#          sleep 15s
-#
-#          kubectl get pods -n playwright-runner
-#
-#          echo "Docker images:"
-#          kubectl get pods -n playwright-runner -o go-template --template="{{range .items}}{{range .spec.containers}}{{.image}} {{end}}{{end}}"
-#          echo
-#
-#          echo "Waiting for pod to complete..."
-#          timeout=600
-#          start_time=$(date +%s)
-#
-#          pod=$(kubectl get pods -n playwright-runner --no-headers -o custom-columns=":metadata.name" | grep -vE '^playwright-runner' | head -n 1)
-#          echo "Tracking pod: $pod"
-#
-#          while true; do
-#            phase=$(kubectl get pod "$pod" -n playwright-runner -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
-#
-#            if [[ "$phase" == "Succeeded" ]]; then
-#              echo "✅ Pod $pod succeeded"
-#              exit 0
-#            elif [[ "$phase" == "Failed" ]]; then
-#              echo "❌ Pod $pod failed"
-#              kubectl logs "$pod" -n playwright-runner --tail=50 || true
-#              exit 1
-#            fi
-#
-#            now=$(date +%s)
-#            elapsed=$(( now - start_time ))
-#            if (( elapsed > timeout )); then
-#              echo "❌ Timeout waiting for pod $pod to succeed after ${timeout}s"
-#              kubectl logs "$pod" -n playwright-runner --tail=50 || true
-#              exit 1
-#            fi
-#
-#            echo "⏳ Pod phase: $phase (elapsed: ${elapsed}s)"
-#            sleep 15
-#          done
+      - name: Install Playwright Runner
+        run: |
+          ls -l
+          helm install --namespace=playwright-runner --create-namespace -f ./deployments/charts/atp3-playwright-runner/values.yaml -f ./deployments/charts/atp3-playwright-runner/resource-profiles/dev.yaml atp3-playwright-runner ./deployments/charts/atp3-playwright-runner --set DOCKER_TAG="ghcr.io/netcracker/qubership-testing-platform-playwright-runner:build_process_latest" --set ATP_RUNNER_JOB_EXIT_STRATEGY=$CONSUL_TOKEN --set ATP_RUNNER_JOB_EXIT_STRATEGY=$CONSUL_TOKEN 
+
+      - name: Get docker images
+        shell: bash
+        run: |
+          echo "▶️ Checking pods in namespace playwright-runner"
+          sleep 15s
+
+          kubectl get pods -n playwright-runner
+
+          echo "Docker images:"
+          kubectl get pods -n playwright-runner -o go-template --template="{{range .items}}{{range .spec.containers}}{{.image}} {{end}}{{end}}"
+          echo
+
+          echo "Waiting for pod to complete..."
+          timeout=600
+          start_time=$(date +%s)
+
+          pod=$(kubectl get pods -n playwright-runner --no-headers -o custom-columns=":metadata.name" | grep -vE '^playwright-runner' | head -n 1)
+          echo "Tracking pod: $pod"
+
+          while true; do
+            phase=$(kubectl get pod "$pod" -n playwright-runner -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
+
+            if [[ "$phase" == "Succeeded" ]]; then
+              echo "✅ Pod $pod succeeded"
+              exit 0
+            elif [[ "$phase" == "Failed" ]]; then
+              echo "❌ Pod $pod failed"
+              kubectl logs "$pod" -n playwright-runner --tail=50 || true
+              exit 1
+            fi
+
+            now=$(date +%s)
+            elapsed=$(( now - start_time ))
+            if (( elapsed > timeout )); then
+              echo "❌ Timeout waiting for pod $pod to succeed after ${timeout}s"
+              kubectl logs "$pod" -n playwright-runner --tail=50 || true
+              exit 1
+            fi
+
+            echo "⏳ Pod phase: $phase (elapsed: ${elapsed}s)"
+            sleep 15
+          done
